### ISSUE TITLE
plan fails on bolt 2.4.0

### ISSUE THREAD

**Issue by vchepkov** [EncoreTechnologies/puppet-patching#45]
Just encountered it, it fails at the very end, while printing summary:

```
Traceback (most recent call last):
	11: from /opt/puppetlabs/bolt/bin/bolt:23:in `<main>'
	10: from /opt/puppetlabs/bolt/bin/bolt:23:in `load'
	 9: from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-2.4.0/exe/bolt:10:in `<top (required)>'
	 8: from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-2.4.0/lib/bolt/cli.rb:373:in `execute'
	 7: from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-2.4.0/lib/bolt/cli.rb:524:in `run_plan'
	 6: from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-2.4.0/lib/bolt/outputter/human.rb:353:in `print_plan_result'
	 5: from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-2.4.0/lib/bolt/outputter/human.rb:362:in `print_result_set'
	 4: from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-2.4.0/lib/bolt/result_set.rb:41:in `each'
	 3: from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-2.4.0/lib/bolt/result_set.rb:41:in `each'
	 2: from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-2.4.0/lib/bolt/result_set.rb:41:in `block in each'
	 1: from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-2.4.0/lib/bolt/outputter/human.rb:362:in `block in print_result_set'
/opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-2.4.0/lib/bolt/outputter/human.rb:101:in `print_result': undefined method `capitalize' for nil:NilClass (NoMethodError)

```

**Comment by nmaludy** [comment]
Fixed here https://github.com/puppetlabs/bolt/pull/1726

**Comment by vchepkov** [comment]
Ah, so it's bolt problem. Thanks

**Comment by nmaludy** [comment]
FYI, 2.5.0 came out with the fix for this included!
